#   AWS CDK example
#   ------
#   Run via: `vinm deploy --stage dev`

stages:
    dev:
        stage: dev
        profile: awsprofile
        account: 00000000000
        region: ap-southeast-2

tasks:
    cdk-bootstrap:
        shell: >-
            cdk bootstrap aws://$vinm.account/$vinm.region --toolkit-stack-name cdk-toolkit --bootstrap-bucket-name cdk-toolkit --profile $vinm.profile -c account=$vinm.account -c region=$vinm.region

    cdk-deploy-api:
        shell: >-
            cdk deploy $vinm.market-$vinm.stage-api-stack --toolkit-stack-name cdk-toolkit --bootstrap-bucket-name cdk-toolkit --profile $vinm.profile --c stage=$vinm.stage -c account=$vinm.account -c region=$vinm.region
    cdk-destroy-api:
        shell: >-
            cdk destroy $vinm.market-$vinm.stage-api-stack --profile $vinm.profile --c stage=$vinm.stage -c account=$vinm.account -c region=$vinm.region

pipelines:
    deploy:
        - task: cdk-bootstrap
        - pipeline: deploy-api
    destroy:
        - pipeline: destroy-api

    deploy-api:
        - task: cdk-deploy-api
    destroy-api:
        - task: cdk-destroy-api